sudo: required

language: python

python:
    - "2.7"

addons:
    apt:
        packages:
            - cdparanoia 
            - cdrdao
            - gstreamer0.10-plugins-base
            - gstreamer0.10-plugins-good
            - libcdio-dev
            - libiso9660-dev
            - python-cddb
            - python-gobject
            - swig
            - python-dev
            - python-gst0.10

before_install:
    - sudo apt-get update -qq

install:
    # Dependencies
    - pip install -r requirements.txt

    # Testing dependencies
    - pip install -r test_requirements.txt

    # Checkout
    - ./autogen.sh

    # Building
    - ./configure
    - make

    # Installing
    - sudo make install

    # Check flacenc availability
    - sudo apt-get install -qq gstreamer0.10-tools
    - gst-inspect-0.10 flacenc

script:
    - python -m unittest discover
